// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugovqizuiyrdbqjabjol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb3ZxaXp1aXlyZGJxamFiam9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTQxODEsImV4cCI6MjA3MDEzMDE4MX0.hElg2ZtT37DLWQXsxD_c3mgbNV2F4vXldLGqjzxtU5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});